
kubernetes::kubernetes_version: 1.16.11
kubernetes::kubernetes_package_version: 
kubernetes::container_runtime: docker
kubernetes::cni_network_provider: https://docs.projectcalico.org/v/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml
kubernetes::cni_pod_cidr: 192.168.0.0/16
kubernetes::etcd_initial_cluster: k8s-primary=https://10.10.100.10:2380
kubernetes::etcd_peers:
- 10.10.100.10
kubernetes::etcd_ip: "%{::ipaddress_eth1}"
kubernetes::kube_api_advertise_address: "%{::ipaddress_eth1}"
kubernetes::api_server_count: 1
kubernetes::install_dashboard: false
kubernetes::controller_address: 10.10.100.10:6443
kubernetes::token: 50b3d7.5a304f3fd862adb7

kubernetes::etcd_ca_crt: |
  -----BEGIN CERTIFICATE-----
  MIIC7jCCAdagAwIBAgIUAXXAagLq2aJ43kFHLdpYleKp0yUwDQYJKoZIhvcNAQEL
  BQAwDzENMAsGA1UEAxMEZXRjZDAeFw0yMDA3MTkxNzI3MDBaFw0yNTA3MTgxNzI3
  MDBaMA8xDTALBgNVBAMTBGV0Y2QwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
  AoIBAQCiiUZQyPZToqrVFSUY8c0lO4OdqXIy6vR/rDQZHskjn6aT31dx4zVxNKFs
  TqGyMaI+eNbLNWF8H9kNmuD+CYZqrY1ROsy+V/olr+M1rVfKgJCTLfGWT7RDlfx/
  Mf0TtdtGZ1v8Lcxr6sgQhpEUxN8JuN9NTKX9sKyCdvtl6a7gzQmcQdaCmT4Vbkvo
  8vjoRqeBN4mt/kM6YGSaJHoLTk73CRx9g2qkrZDf/DdL2EhvsV6s7ANdnsv6Qsxz
  E/Y3z29P3HNTXSA90plNPudCvYpP9R3Owzp9VSDN2GmKRnNsr19RNm0gENhYwbF0
  GIHfIDHASnyvyFkQ4nAcBoHD+fBNAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAP
  BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSDYybKCHgX61qhSvwfEbQOheQ2gjAN
  BgkqhkiG9w0BAQsFAAOCAQEAmUeKJ4Lk/rykPRZR8DFazsi/yHAjDI0117s8wfDD
  sh6R8ibdg/6gFdXZ74bH6EXKXJVW505AVu/Fsh/gKze5Fm0NVenv/p9JkpCppAlk
  IbvLQVdcliXw43LVf22/c8+dFxq0Gz7v0SrE9D7v/HGHSIkPiz5hN5pTPVO62qF+
  bDt45tJFuYp5OAPF4h0VAyUFEoXLCSSOrawFrCizaB0FvzvJwi5HnVM6pk56P+yw
  kZBsEZF0BxBp+0+aUH3gyUXbN4Q0OcuOR9QT90hJ69eWCYKGeFXnMxpt7+6u/Rtz
  XtuwvhESCrtQ0qATDULfrx4CUliojsAFQj25PjL4n66a7g==
  -----END CERTIFICATE-----
kubernetes::etcd_ca_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEowIBAAKCAQEAoolGUMj2U6Kq1RUlGPHNJTuDnalyMur0f6w0GR7JI5+mk99X
  ceM1cTShbE6hsjGiPnjWyzVhfB/ZDZrg/gmGaq2NUTrMvlf6Ja/jNa1XyoCQky3x
  lk+0Q5X8fzH9E7XbRmdb/C3Ma+rIEIaRFMTfCbjfTUyl/bCsgnb7Zemu4M0JnEHW
  gpk+FW5L6PL46EangTeJrf5DOmBkmiR6C05O9wkcfYNqpK2Q3/w3S9hIb7FerOwD
  XZ7L+kLMcxP2N89vT9xzU10gPdKZTT7nQr2KT/UdzsM6fVUgzdhpikZzbK9fUTZt
  IBDYWMGxdBiB3yAxwEp8r8hZEOJwHAaBw/nwTQIDAQABAoIBAF/pY63uOLV3yxk8
  hgynO2haKzuRLwtu7GKeqoucSBMWdcTSyZYx/mpUJWF1MSOm+FenFREK6gDGBl5p
  45Tk6AXxbe/eI826uqkclpYpOSINJcNEHEiXtgcf7cTdKbtE2CU+fuBb4kJYZECk
  N96qofbpuhOyRE1kwRenwIgOEp0iUAistafev0lnnx9Azy1yGE2kGIN6X6xfihv4
  RI+rEIpDVaPw620gM0YsUOxN0BnR2I9NN6pH7JgJSeUn0YFHeF5h9EHu9TSti7YB
  VI84dC4lAkkCUF46UvbYmVbUMz8wLwJ33hdu87OJflTjAaSX0sOctJ9ix41upnav
  S1DInYECgYEA16wv5TyZftYAk1pQXOUOde+VTLnSB3h5Pv4uCybJNClleKwqD+hj
  gzFkuX5oeYVE88rhnIiTv/eoFom4WKZxAhewkagPuB8ocrLWUk6iwx/d5ePjE0XB
  lEJarDuEo9HPcYWhbjqUdKbk6IhQX8NA3ZzLNGIT/IEalBwogBHV9CECgYEAwO2O
  bAYH9gEPLR2y1Ms6pQDY2v46jPY5DgHIbGQP9nkD1+EPbk2Biv7Kfq3FMtCKjCVA
  PutXODPymXvpRUt1mPuMA4kp5EDG8YlouvkQBnKM31jX19TJk7MV/uzKOwgwIyh+
  4DnOX1KVzb6DwX3kdNz0oGqfeHLaB+e1DshFNq0CgYEAnhUq4iciB3MK5vcK8pw+
  ljlvQNbvWOR4UrDyxN/AGQjCxMnE5vYagt4gi0pZf8EsglnSNu9xBQOdZC+8PNZ6
  /OKqXIlIRFgqSLBHIftbmBRyjIAWQFkgA/EDDz1tArrWB8rAQdCUYlC2dq774sV2
  dTnpRFMjfTCQb8GX+g+YuKECgYAoei7lbyaAcJx0hMSebL0zHUhiOfCi3o396FXa
  l+vZdG5f/rI0HELPnMFzbpXvIV3QJYijKtEz04JUvXClvz0/CZfIriCB6S1UQ9Yb
  VGIOWD5CJeuzNsvMF0jIIXoUhJVE6xwjgz1PNo6DijMuh3FFK46PkY8/wCkKe4y7
  Oz16SQKBgDkVFFeKRX7R6q/l7L2MUja8iWeovLi4fU3RfxORp9kXCD7KA8md7sCL
  yxI6C/5bUl2TsZBQZc1qhmm9uMwv2gDon6fd87uNyTgUBRF2cW9o1bNbnBvv8Sm3
  rCPmhDg02ej+1H7LIAJKq7KSRDL+9/mRsiulyudlhN/anXVV3+vi
  -----END RSA PRIVATE KEY-----

kubernetes::etcdclient_crt: |
  -----BEGIN CERTIFICATE-----
  MIIDMjCCAhqgAwIBAgIUAumJ4klGpRRuifPWE5fwnu1qiDAwDQYJKoZIhvcNAQEL
  BQAwDzENMAsGA1UEAxMEZXRjZDAeFw0yMDA3MTkxNzI3MDBaFw0yNTA3MTgxNzI3
  MDBaMBExDzANBgNVBAMTBmNsaWVudDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
  AQoCggEBALZQ3IoGht6lbKI1KY0NSqxPEZLCDUz79d7Yfg+HYOeVJjhbHiCaz96r
  DiN4jki1lhgxxTMoi1yf4AHeJh1wEEgYGRYCgL7fAu0vDOg1HErujq3iCqNRCBHI
  dJAV4tl19WZV5pMOTmmH9LCfcglhKhQHVkI0GTQPdjpUQjlANlSzJx0Kj1TXovkr
  YI44D251BxLpvuH9bdZjlUmKn7PoGsWrG/Z/nkSOIUhZDEEcKXX4ofsSWw2SgEk4
  1IoNyzSs7dKqDaUwvg9JaUB9ZP4qIEKBtZWKhbEaWhB8nlb16lmdMfKgIwfV0POK
  05EZSnfRxnS8h8iaA608LZmeQGAKRiECAwEAAaOBgzCBgDAOBgNVHQ8BAf8EBAMC
  BaAwEwYDVR0lBAwwCgYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQU
  TUtfgI5zv/ihyUlUsykY1EQXJ+4wHwYDVR0jBBgwFoAUg2Mmygh4F+taoUr8HxG0
  DoXkNoIwCwYDVR0RBAQwAoIAMA0GCSqGSIb3DQEBCwUAA4IBAQAxsK0rstu8agMM
  Gy1S6Ng11Ry8Sf7l9JQurz6mSW93/y/P6ZOw0LzaYGG1SXX7a3VNyNSslmK2IrBb
  ETrGobpnVt247k/5h5lPJrocLXuftsfeUBOqQN0a+cHNoh+Nf3s4gV3SvtML9rtC
  NvqwWaKpacwnkovhMbOxa+09/Uv4k9cQMbOt8FgDwDDc1POSNofJX2eTD/jZISB7
  AhR7pEkfEWfJf7w0vRuyJoXF7AJTxMgTdCxWnpJppKv3b6I7uh4+nMPmOb6EjOkr
  s4beYsXWBYcAzTLFwir+uCLuN6hplyCM2MWZeYPCo5tOnEYlF8mC59VaLkjTxP1x
  ZAO/5bEO
  -----END CERTIFICATE-----
kubernetes::etcdclient_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEowIBAAKCAQEAtlDcigaG3qVsojUpjQ1KrE8RksINTPv13th+D4dg55UmOFse
  IJrP3qsOI3iOSLWWGDHFMyiLXJ/gAd4mHXAQSBgZFgKAvt8C7S8M6DUcSu6OreIK
  o1EIEch0kBXi2XX1ZlXmkw5OaYf0sJ9yCWEqFAdWQjQZNA92OlRCOUA2VLMnHQqP
  VNei+StgjjgPbnUHEum+4f1t1mOVSYqfs+gaxasb9n+eRI4hSFkMQRwpdfih+xJb
  DZKASTjUig3LNKzt0qoNpTC+D0lpQH1k/iogQoG1lYqFsRpaEHyeVvXqWZ0x8qAj
  B9XQ84rTkRlKd9HGdLyHyJoDrTwtmZ5AYApGIQIDAQABAoIBAF1Hc/7epgSmSLWZ
  U6AKa+lLLyeSR3Ha/Ao/ZAgX8Nmr8vkkjX6LFs3LYRl+5fWHirroRAgPt3X1iowK
  GCA5pOruAW/EahC+U2X9C7KG8enYsoF+xIiYvfMzR4gs2nr+okbwrl8RE8dkuyne
  +l6YKwpCUrzeoQKE4q2nTJa0JtggUBYJ0Qgs8LjN79JowXnawDDpbrDcbAWh4mry
  ABodEEIzeK/cM6YxWz15oBieyJKOweiJJm52iAIj9tBq4OlSeYJKpf2KyhPEgkx/
  n3/C1Z6mot4BL4YrX746XJqksKVEuu7JhPuIgM3Xz/3gXcaAj7yuGZXysJu6mYev
  hFnyT60CgYEAzlIQ0lRFH41wF3mEsz9xZ6LOb4qwqe/Ne4JhmfyJoguXEPgCre4a
  TCJW06xmQ/77aBgVU41pKtB1fqokaS1LF7XRgvsBV4HXjSP/oT1w25YkOC1PM0+D
  fwnK0dFAn8XPseNtsH8ZItXuVhwPtLbtxpCuNYTybQQlNKh5iQ33xo8CgYEA4jcb
  XmSMnMz0bTaf++mol/dSD8Owb/6i7TkXDrWJEg2U04xVn6x+7C0UV2xem2fFSG23
  81ccHVQWBRa1W33yT0Exj3cv1rPP+u7AkYs/XosuxtNO8GMEi1pqh7AEf9hcFbgN
  BB7NLxBEyo4VkQdRgqBEuXCJfu23ea0xqhAsAE8CgYAfalmLXS+FRWkK+gLdtExV
  RnH+g/Swe4YjR1ALPWvLk8411D28NCQm8Zec9YRA2EN5rykYJtEbptAtMEUJCs+D
  VbkII6Ypp+ilYhTbfVqA5RSwxR1pJ7NTFa+fUShw65LbeFDMbh3qsv5ueClgD/aW
  pJMSLSMovFfZ88lFuC3BOwKBgGZihrKcU8AMS3y6woIj6TiOqceUzGCEIX243yS7
  KUTQfNGarI5OZkvCw3gmBlPUDciQUDeE76aejjDTbFXylR8l5KaITVChpbpvIR0+
  pvnFiPBYZ1wJlN71l02+burmJBd4a/u3bSql9FyxHjW72DqFC1XbB4A5W1do+hd8
  pk2lAoGBAJazssyxibMLl7q473UpKyjiA1VQzVxgy6SmDst6Rt+4yrZg/lXYCNYs
  LL0kwAfQlkl7yvqAsK6U6fMPiiv9ABaXm1mLSA8Pq8kBpoKyHbHZDj0Rk0BglxYs
  8+Wfw4iIbU6mCJsOAV+60TeLr1WOjA3KqgJ/rzwqMYDa0eTFU9hv
  -----END RSA PRIVATE KEY-----

kubernetes::kubernetes_ca_crt: |
  -----BEGIN CERTIFICATE-----
  MIIC+jCCAeKgAwIBAgIUI8OEpo6MzjaSksMRFgIuxnavlEAwDQYJKoZIhvcNAQEL
  BQAwFTETMBEGA1UEAxMKa3ViZXJuZXRlczAeFw0yMDA3MTkxNzI3MDBaFw0yNTA3
  MTgxNzI3MDBaMBUxEzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEB
  AQUAA4IBDwAwggEKAoIBAQDApmldqdW2STktvEVUnCFE8oMRLm4rzRCtfJUp2KMA
  xN2pJKNAvrNNSRMwU6KCn2otPeh41AeCQS7bsxBDAggB4lJ7G27KkrCXR/7n9cgA
  3C0iTU7dpuIqoorfrUp4T6zXxvG0XQWQLId/WtFvp0sWDsnA3pi1JGsXf4VOejXk
  61VguaPiomBLxQPpAnxbaehdyiYWHbyVFKGE28xXVQMkv3bXjCF5lPe4Pqr7W/ra
  IZzuGCtlxMG0y5V24dprc8oPGgYLdhM/Wye/0pW6RGEEu5DeLGrxywC4CCr94f3j
  cCFEoYR9V5AZS4H1fJpHqKNMaWPovKB8WNDvvWA8VrmTAgMBAAGjQjBAMA4GA1Ud
  DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRqQmE7ZooHripG
  WdEWOVLUf5Fa3TANBgkqhkiG9w0BAQsFAAOCAQEApI1mK5irVrx3m30Q9r8Aj8X0
  bWQbEN3i/hEh+lih17rHc7CJuWBpgwhTJSPvJpXIkZUWtfHg1CRK6wd1vuFQt1zy
  Iy4Amj/pzdO+H/hjrJt+iJ6MKC6PmO09rHJxNPApq4Q3n63Nqb7uuIQNTfGFYa9I
  Oo0dnp1BfsjrfK+9oln0N9VI5swvi8xv69xGJ6gqqOkmQG7Txn3wvpnexdDt5Oyu
  qUTix/qIJSkUIC7UQNBpoM/5Erv8BkmclQzPPt/XVGH9RmGSSMySJrj7La5LSu3M
  1DQ58+FquEhNn+h4obrenT2kjJ3RiaVpzvRj1RQ7X0uVIUF47Kklj163yiZxYg==
  -----END CERTIFICATE-----
kubernetes::kubernetes_ca_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpAIBAAKCAQEAwKZpXanVtkk5LbxFVJwhRPKDES5uK80QrXyVKdijAMTdqSSj
  QL6zTUkTMFOigp9qLT3oeNQHgkEu27MQQwIIAeJSextuypKwl0f+5/XIANwtIk1O
  3abiKqKK361KeE+s18bxtF0FkCyHf1rRb6dLFg7JwN6YtSRrF3+FTno15OtVYLmj
  4qJgS8UD6QJ8W2noXcomFh28lRShhNvMV1UDJL9214wheZT3uD6q+1v62iGc7hgr
  ZcTBtMuVduHaa3PKDxoGC3YTP1snv9KVukRhBLuQ3ixq8csAuAgq/eH943AhRKGE
  fVeQGUuB9XyaR6ijTGlj6LygfFjQ771gPFa5kwIDAQABAoIBAQClUik5Z3UuaMfY
  p6gXY6RpNnOjWuTQUbnuJusabf3zuv09GWO/O+dCe2MsJZlf3s2O5YGJruqCrM05
  XACogCW++Ckv2+rHi/pe2Dm3dQOdOVTCCvWS4JNVYwcpy9wMQtNgmCjzTqBniM7+
  S0FPP5D/7NDV4i/Jwubj01ribZ2yQ4Og2yjIc9R9wDX0wLFEyXHGf1K3/6j767Mo
  uKiwnZU69h9Kw18vQQ7i5DLphDzKKMNO1/RZmcjODs29/ZwjSBm/L09uhOh+Y69e
  W8CS9HKknhVNECuuIxRnChg7GcxPJvUy3Zbm+cnflBSHMJDvzhluiAAYJyCmDoNE
  0W7zzqKBAoGBAOzJxIOWM7myaLp0fsMYE4063WmCVDXMbOhq1+trhq3sohchJ8Zt
  XTVgCqnMQaatshY5t71MhHFvvUjtoqN2Ougp+Ls1/tApIkEaVNaXCeyxENvJaNsD
  Df9b0goXHfEmQhmma3MQCp3qitlWr0HaXJTnDX5X8XmH6GIRRWxOq6bHAoGBANBH
  3m6TPTZuu62lymo3fW+syc8LABJ+Rg+tXukb2ICpBgV4npMwMfDwL9Os2VXIfJMN
  GydM0ukttyPD+DtAN/L6IwvrAQafTp1ek4ci/KsgiU5EJt0RaU+uFHvqizVD1DWs
  1mWZNt/cBrQA4cYbuydkZ9jkcXUdcltodh1rBVrVAoGBALVnXkXxLG93XwR5eyO7
  rj7kefv6/Mi6dDUapZCWL/fO8d8GZ5J89ouNqJ2s/h7TszuTvFAp7s147WqRo6fX
  TAnRHd1O4IhY+wUlRxmfXNsYS/IVu18OWArqLV/NlgLJbJp6BJeCEqAor3cSEfJB
  d+wblxrUBQs2M7HtyWHQY3DBAoGAd+8KjI3Ij9GPzNxNBIDTgDz1MH3bGssPuPNS
  VdUtBFlQGFJurb7w4xbL044S0CzUXzEK08SPJqqmbLfp9uRx0z5qc/Bs9M1DTacq
  OITTDg98QU9JOb9O7w0Eyp4ybweR6R6Pjo19ZcajLX/cgmFxkatliSVyl8fPFAfB
  DAuWV8kCgYADNf8HB8SHZDoJrx/V2dtFJvggQCvQMx5H6mzVq16VWk5gdvIEECfI
  n5u74jxxIsfEi4Vit/9Z14o1EBeRuwymYwUpjC/NHhvKTWJibcKSUDlkRF6pzzHp
  VpW/6Bqz9MANgNriXDLcOg/GGrJ4q3GGMew1UuxUtC/rcFO98lQJXw==
  -----END RSA PRIVATE KEY-----
kubernetes::discovery_token_hash: 723b0a2ad06a06e244db8965a7be5048da1afbbb34dfb13db38374eaab195066



kubernetes::kubernetes_front_proxy_ca_crt: |
  -----BEGIN CERTIFICATE-----
  MIIDAjCCAeqgAwIBAgIUMzK9fBD6/+cb5Q3Uk1ZU9Jijy6swDQYJKoZIhvcNAQEL
  BQAwGTEXMBUGA1UEAxMOZnJvbnQtcHJveHktY2EwHhcNMjAwNzE5MTcyNzAwWhcN
  MjUwNzE4MTcyNzAwWjAZMRcwFQYDVQQDEw5mcm9udC1wcm94eS1jYTCCASIwDQYJ
  KoZIhvcNAQEBBQADggEPADCCAQoCggEBAKSUsqHDy7FW4ve6up614UgW682HZxLE
  L1Du+VegLg1u/zGliJI3hLBaYb+1edT0oEwWqOFZqVgiWyTBB7tgqwJQmrP8IL/2
  TgWcK1OklJOmIQQRauThb3L4xrigvnrdn2QSOkS5wGZgE0p4jB+Rc3ZMCyDceIn4
  FYa9CwL0jQO5UyCcuh8BhfRrTsO4CplgPgZ1aqxlwv5rm8s5jr3VtcpRFWG31Qas
  XCxCowrO0Xv9fsmtaLtqq2AgKW7LmIVegCo7sK3oM7Tz+9SA+jMBtLGSV9dO0pRJ
  Fz9ULXr7xmjsgO94xLaKEbxg91PRYHMAOwkoi29c0ZhKGPxqEuOIYA0CAwEAAaNC
  MEAwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFCL4
  bwNpWSZBQu8ap0XsgmDxx6QVMA0GCSqGSIb3DQEBCwUAA4IBAQAZMWB43XzATHvk
  phNnGlCjtbtbydVs6czOn3boPAQdOoUs0pWLd4Uic+Fub7prF92RhjGOWeEDDUE/
  ts8JVoFkjIFkDHt8dvjTDaGBM9Vcvz6zKn0+BFl8tY2TSSmnLQ1kxgUJzFkkGAK3
  aAZiBF7RR/cZtQ4xknsRx18uAvsxmNnhy+syfUOh6gbnpgVQ9w/4tOzH3/uYWo8F
  ujfIVrFkVFmV4Gci/SvHT7BLEEl28S9BsxIRiFKCSFRCRV+DHCPHfgOQnAdv0+CT
  ZFysSirZJ/OkBKPytzdtEMZHbfL3dh3GvdzxjqwVG2PBk59Kdtdiz/fUUqhkKAAc
  Jo+xkqA2
  -----END CERTIFICATE-----
kubernetes::kubernetes_front_proxy_ca_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpQIBAAKCAQEApJSyocPLsVbi97q6nrXhSBbrzYdnEsQvUO75V6AuDW7/MaWI
  kjeEsFphv7V51PSgTBao4VmpWCJbJMEHu2CrAlCas/wgv/ZOBZwrU6SUk6YhBBFq
  5OFvcvjGuKC+et2fZBI6RLnAZmATSniMH5FzdkwLINx4ifgVhr0LAvSNA7lTIJy6
  HwGF9GtOw7gKmWA+BnVqrGXC/mubyzmOvdW1ylEVYbfVBqxcLEKjCs7Re/1+ya1o
  u2qrYCApbsuYhV6AKjuwregztPP71ID6MwG0sZJX107SlEkXP1QtevvGaOyA73jE
  tooRvGD3U9FgcwA7CSiLb1zRmEoY/GoS44hgDQIDAQABAoIBAQCfa5Ik873JSDqO
  cIf42IEiDWHYMoJ7QSH8KZ/Ja1VwmcYEVy4VREX5dXMd+jHLQDJNwd1QfEN3JcBX
  t8s/jAHaOi3AjkdC6tjkwkONv+xToSZ2BFEg5+XG3ofPq5UW+ro8exOKIsvl3saQ
  6ngA1Cmdu0dES4tPScnAPDoAYNZ/dWT8+jbwBHMF8yyR3q977vSi7inhk1vEM6pa
  cqco54mLJaRgyJ90U5Lr0tSDYN3YBC7aM9/HMY2NP6uCUM8+k8jRYNcjv9JkKoEI
  5D62EVH0PSCgb9MTAPMXSVg6M9Ac2dwWmq/DpfvP/i/83Ey00VCESN8adYoMjS5M
  5K9+VnhZAoGBANFxW2hKE5O3m5s4psQoQGaI0KgHs/P9WfPqDGWYnjv0wCF0kxE0
  RjAOfCoQT32GGfF83phFxHGKz8b8jKwC9kIBv2HCZPZ3vz8XxPAtUbobbDFNvagN
  KO5zbs2/xjjW7PXrOmAOamqEiOjv71qYdgUmjU2SOhehR8hhtW34+2KTAoGBAMkq
  aDgFnS0lDNu2UQaWKptKwavLowUAw8iE8iYO46KywG9fLK8fXrcI++dXynu+MrFq
  L86ycKUv26L382DQLTD3e3m4U5bHpJTp0HQ3avTD4gL2k1Zwn5ci94wHEi98dLpN
  KrZhfzyq976pIVZIwHfijWuUnC3tVXTVT+IUQ7bfAoGALR5EWLUMfpfhF5Eeq8cY
  CH6UpH30UC1VwWu7++7it3vEH/Di9aPTMusL6GvXE+1djV4e/aKZ7PPASteA3lVN
  A28o8UBVS5sEQe026Z55qqPZrM1Ye+lJ1gRb7ErRwtDZ/ygLTUINvqCKddOqNlP9
  qKJjckB77zc5JXuW//fQ/60CgYEArWxsypc0aH3/ds7XTXlaI+Sv0F5PHPoKzyyl
  4V+GqXW25ozDZfoCWoNZP5j0y/ctlru3mVdGO3JlxDpETBtMSmGgxk+9aEiWv3ZP
  KlG4WGkiyHEwlh2jx9TyWnqiF+QQcagjAXZODcxKpskCH3O60d+zEaLdfc6UlJNt
  ObdEpTsCgYEAqqEQgGFTsSQfDSaaisd8lyqzGMH6uc+tFcF/KOVitBUj0ymmQshT
  e4jImgnTZDKO07PgOnse2b49frxWgtOrh00aiECqaGcsy8ruC8VToTEzbxJIPNrv
  Hmp96/mGqmxgCU9cMKvKC56tHW/QRe+QDnfbugIOGR/3JNcw6q3vNYg=
  -----END RSA PRIVATE KEY-----

kubernetes::sa_pub: |
  -----BEGIN PUBLIC KEY-----
  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2rrL3lt4FkO/7pnsGWm+
  nk9mfEg0XNIzHoqN4onNlyHOxs7g/3xOVkWIh94wEArqyNATRmI067VQyAs7EMka
  KDXChty6Tp+rLPcCHnlALmyvgNJIZFLBFzg13RINbXzoRH0/RhyPwwESuJzY37f7
  84DQg7GTAkTD6DrzYLpalwwLv+LvmOPf86APePRHSKx+1OL9I9dIM8anMnfzGlUp
  hRKRmfVFacj7sPXKt/ojtUD98OL4P91OwTuG6fiZnNDbH+/40MmOCTedRYfBlIz9
  Q89W2FtV1WeaX2VvsEmGlKEL0v7VC1hr9UVsVMwd4W7cl/5prMb6QTiDzIk1ll7V
  qwIDAQAB
  -----END PUBLIC KEY-----
kubernetes::sa_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpQIBAAKCAQEA2rrL3lt4FkO/7pnsGWm+nk9mfEg0XNIzHoqN4onNlyHOxs7g
  /3xOVkWIh94wEArqyNATRmI067VQyAs7EMkaKDXChty6Tp+rLPcCHnlALmyvgNJI
  ZFLBFzg13RINbXzoRH0/RhyPwwESuJzY37f784DQg7GTAkTD6DrzYLpalwwLv+Lv
  mOPf86APePRHSKx+1OL9I9dIM8anMnfzGlUphRKRmfVFacj7sPXKt/ojtUD98OL4
  P91OwTuG6fiZnNDbH+/40MmOCTedRYfBlIz9Q89W2FtV1WeaX2VvsEmGlKEL0v7V
  C1hr9UVsVMwd4W7cl/5prMb6QTiDzIk1ll7VqwIDAQABAoIBAQCHNkwKs96jXNRM
  KkiiWRUmBg1jrLr52lMRgTM+pFM8JwENMxwxs2U1vZwt6XMqp6UF6GLR8qmmQBqk
  3xRvRvHtg3YyKkbdjaSikjt0HR5I1JUVfGiV4/ZLZUse0ycL1Ng8ZnRz4foY4RPy
  nbsPaUvN9oZvspkfIOU+LRsAY5LWpc4O+3Iacqj0r3aedzrSdjuYc9Q6GqIwdQDA
  E++PLx1Ar/xE2B58dEzTv2VeZV9VFSgq7hyrt+V5yxU1thhrqSjralkk+pdipaTw
  46is+QA0ytNWb9ymCmsd3OD+2dXzAG64et4ZSqxrDIH9VAa1uk2x7kTqtzDpyyjB
  tOZonfkBAoGBAPCp5IlGIJgH7KCndsFoNG1fd4/HWar+OXbEUaRa2QyRdaO0LUkJ
  gumzUCB+pJb33zomd1iRpqc5MWBG5b51Xdew4vVvtFDSthEwSP5nJIcBqjcNFtfP
  iMBPSV+U19Uh9I/HaJXFqeUS2uBRSAy0fj01kDbqwuP9ZJLCg0dCohIrAoGBAOir
  FIC8uhjRJv35jBLeDgkjeqBWNeRdzVTlf3BWvMwqO4qw5Tcbb7KjLVuHabJCRdiX
  mGIqoVYQIkU3O3x0Eb30BN1RbR7zLWZ031yMEw3DV55A8bt5tZGtbsqoQCQhu1eZ
  GkP49Vhlya9YFRl/yag/npo7Hj5VZOa9dv7Q+gqBAoGBAKqc9uyur5q4O3PlZNZW
  RpynSn6+p/4GPrzJDswCr88uLAUDTftyZ8HAInT28z4nubRi4scCcvAoJq4HdQZh
  9EZeG3g+WcnWp8ZlwcnBW27uqjpe6CvU8DDNxMmjHqP1b4iiqK1NNVW12T+fwAFp
  z/kayQN1yPaShENa7HCPd5CDAoGBANoG/yaINAdvbw+OGnHPve1YXuADCWtfbzt/
  98TosvDLHpKfo5vZTPlkKevcX/KYYeVOYZCUDC2e3s5nrIm6JqoPEcPnOs9G56Nc
  H7cU2AIMrH1ytFOPANNrZyfnNHvnVCwJH3DUyew1LiLu8o67jdfpDhHPFk8pLG2A
  3BJ69+SBAoGAFLrxkvRtMTc+A1y84pzdl0kugJcpAb/bxaJ8Shx3R7DnE+9e1b4z
  WctUf+DYzUB9BJxPb+ecxGEQj8MKi5exyac1QIr8H7Oy0+3X3hyMLkdb8ztk6GZD
  t6cmDwWCg35Im6uZl/mrOX/Y7IjMAROWTu1a+0VEOLkv7SlataVmVAc=
  -----END RSA PRIVATE KEY-----
